name: marketplace

services:
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        restart: always

    database:
        image: postgres:latest
        ports:
            -   "5435:5432"
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
        restart: always

    marketplace:
        image: bxrbasov-marketplace
        ports:
            -   "8081:8081"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
        build:
            context: .
            dockerfile: marketplace.Dockerfile
        restart: always

    rate-service:
        image: bxrbasov-rate-service
        ports:
            -   "8080:8080"
        build:
            context: .
            dockerfile: rate-service.Dockerfile
        restart: always
